### ISSUE TITLE
Compile turn on error in nroots.c

### ISSUE THREAD

**Issue by zhouxs1023** [georgeweigt/eigenmath#13]
Compile environment：msys2 x64
Compile turn on error in nroots.c as belows:

nroots.c: In function 'urandom':
nroots.c:303:32: error: implicit declaration of function 'random'; did you mean 'urandom'? [-Werror=implicit-function-declaration]
  303 |         return 4.0 * ((double) random() / (double) 0x7fffffff) - 2.0;
      |                                ^~~~~~
      |                                urandom
cc1.exe: all warnings being treated as errors
make: *** [<builtin>: nroots.o] Error 1

Then I delete option -Werror in makefile 
compile as below:

D:/ProgramData/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: nroots.o:nroots.c:(.text+0xda2): undefined reference to `random'
collect2.exe: error: ld returned 1 exit status
make: *** [Makefile:15: eigenmath] Error 1

**Comment by georgeweigt** [comment]
random() is part of the Standard C Library so this is a compiler bug. (See man random)
Added -lc to make files, this might fix the link error.

**Comment by georgeweigt** [comment]
Changed back to rand() and RAND_MAX.

**Comment by zhouxs1023** [comment]
Compile latest source ,turn on error as below:
gcc -O0 -o eigenmath eigenmath.c -lc -lm
D:/ProgramData/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lc: No such file or directory
collect2.exe: error: ld returned 1 exit status
make: *** [Makefile:4: eigenmath] Error 1

but I delete -lc in makefile;
Compile latest source successfully

**Comment by georgeweigt** [comment]
Removed -lc
