### ISSUE TITLE
help for cubic root calculation

### ISSUE THREAD

**Issue by goldjunge91** [georgeweigt/eigenmath#15]
Hi
i want to calculate 
cubic root with division inside in python it is working in this way 3.4*((mv/obd)**(1/3)) i tryed copy paste but your software don't double star and closed brackets :D
![Bildschirm­foto 2023-01-15 um 20 30 49](https://user-images.githubusercontent.com/30201929/212562905-03731474-bb0e-40d9-980d-cc8ba9c3c766.png)

**Comment by georgeweigt** [comment]
The caret symbol ^ is used for exponentiation instead of **.

https://georgeweigt.github.io/eigenmath.pdf
