### ISSUE TITLE
Suggestions for License

### ISSUE THREAD

**Issue by chirsz-ever** [georgeweigt/eigenmath#2]
Thanks for sharing this great work on Github!

In the License file you just write "FreeBSD":
https://github.com/georgeweigt/eigenmath/blob/6967b5a5ac302c811538d3146bd600ade74de30d/LICENSE#L1

It's confusing, because there are various "BSD Lincense" (You can find them on [Category:License](https://directory.fsf.org/wiki/Category:License)). The "FreeBSD" lincense which you wrote is like a specialized BSD-2-Clause lincense for the FreeBSD project.

It would be better to clearify the license. On Github it's easy: 
1. click the `LICENSE` file.
2. click the `Edit` icon which is like a pencil.
![image](https://user-images.githubusercontent.com/31474766/70862446-a3ecdd00-1f77-11ea-8293-b6d444153673.png)
3. click the `Choose a license template` button.
4. Then you could choose a license template (Github supports BSD-2-Clause lincense and BSD-3-Clause lincense) and edit the related labels, then you  could review and submit the change.

**Comment by georgeweigt** [comment]
LICENSE file fixed, thanks.
