### ISSUE TITLE
express:"--2 * 3"  syntax can not parser!

### ISSUE THREAD

**Issue by zhouxs1023** [georgeweigt/eigenmath#21]
++2 * 3
+-2 * 3
-+2 * 3
above express can parser correctly,but express:"--2 * 3"  syntax can not parser ab below:
![error](https://github.com/georgeweigt/eigenmath/assets/905931/30a776b2-3e0b-4a20-ac6f-e784ac9ba0e1)

**Comment by georgeweigt** [comment]
-- is a comment
