### ISSUE TITLE
integral(x/(x^3-1),x) can not integral

### ISSUE THREAD

**Issue by zhouxs1023** [georgeweigt/eigenmath#22]
integral(x/(x^3-1),x)  and integral(x/(x^5-1),x) can not integral
![integral error](https://github.com/georgeweigt/eigenmath/assets/905931/7adcfaab-8f98-4f17-9cca-1d3fe7eb9192)

**Comment by georgeweigt** [comment]
x / (x^3 - 1) fixed, won't fix other one
