### ISSUE TITLE
Generating prototypes.h header file turn on error

### ISSUE THREAD

**Issue by zhouxs1023** [georgeweigt/eigenmath#26]
OS: window10
Compiler: msys2 mingw64

I turn into eigenmath/src folder,then make clean, then make , turn on error as below:

Administrator@XTZJ-20221117KS MINGW64 /d/Demo/math/eigenmath/src
#make clean
rm -f eigenmath prototypes.h

Administrator@XTZJ-20221117KS MINGW64 /d/Demo/math/eigenmath/src
#make
make -s -C ../tools make-prototypes
../tools/make-prototypes *.c > prototypes.h
cannot read alloc.c
make: *** [Makefile:8: prototypes.h] Error 1

Administrator@XTZJ-20221117KS MINGW64 /d/Demo/math/eigenmath/src
 #.

**Comment by georgeweigt** [comment]
Likely mingw issue with stdlib calls in read_file() of make-prototypes.c
