### ISSUE TITLE
Can this project be compiled with Visual Studio in windows?

### ISSUE THREAD

**Issue by zhouxs1023** [georgeweigt/eigenmath#3]
This project is very good，I like it very much, I want to know thar Can this project be compiled with Visual Studio in windows?
Thanks for your reply!

**Comment by chirsz-ever** [comment]
It could be. But this version have neither a GUI nor a Visual Studio project file. You need to crate a new project and add the files on your own, or you could use mingw then just make it.

**Comment by georgeweigt** [comment]
Maybe, if VS can build a shell mode app.

**Comment by zhouxs1023** [comment]
Thanks you,I successfully compiled this project with vs！
