### ISSUE TITLE
Is there a development document？

### ISSUE THREAD

**Issue by zhouxs1023** [georgeweigt/eigenmath#4]
In order to make it better understand, whether development documents can be provided？

**Comment by georgeweigt** [comment]
See defs1.h

// Symbolic expressions are built by linking structs of type "atom".

//

// For example, the expression "a b + c" is built like this:

//

//  _______      _______                                _______      _______

// |CONS   |    |CONS   |                              |CONS   |    |SYM
|

// |car cdr|--->|car cdr|----------------------------->|car cdr|--->|"nil"
|

// |_|_____|    |_|_____|                              |_|_____|
|_______|

//   |            |                                      |

//   |            |                                     _v_____

//   |            |                                    |SYM    |

//   |            |                                    |"c"    |

//   |            |                                    |_______|

//   |            |

//  _v_____      _v_____      _______      _______      _______

// |SYM    |    |CONS   |    |CONS   |    |CONS   |    |SYM    |

// |"add"  |    |car cdr|--->|car cdr|--->|car cdr|--->|"nil"  |

// |_______|    |_|_____|    |_|_____|    |_|_____|    |_______|

//                |            |            |

//               _v_____      _v_____      _v_____

//              |SYM    |    |SYM    |    |SYM    |

//              |"mul"  |    |"a"    |    |"b"    |

//              |_______|    |_______|    |_______|

//

// Programming notes:

//

// 1. Automatic C variables of type "struct atom *" should not be used.

//    Use the global variables p0-p9 instead.

//    Call save() before using p0-p9, then call restore() when finished.

//    The use of p0-p9 is required by the garbage collector.

//

// 2. Do not use NULL for a car or cdr.

//    Use the pointer returned by symbol(NIL) instead.

//    The code does not test for NULL.

**Comment by georgeweigt** [comment]
From defs1.h

<pre>
// Symbolic expressions are built by linking structs of type "atom".
//
// For example, the expression "a b + c" is built like this:
//
//  _______      _______                                _______      _______
// |CONS   |    |CONS   |                              |CONS   |    |SYM    |
// |car cdr|--->|car cdr|----------------------------->|car cdr|--->|"nil"  |
// |_|_____|    |_|_____|                              |_|_____|    |_______|
//   |            |                                      |
//   |            |                                     _v_____
//   |            |                                    |SYM    |
//   |            |                                    |"c"    |
//   |            |                                    |_______|
//   |            |
//  _v_____      _v_____      _______      _______      _______
// |SYM    |    |CONS   |    |CONS   |    |CONS   |    |SYM    |
// |"add"  |    |car cdr|--->|car cdr|--->|car cdr|--->|"nil"  |
// |_______|    |_|_____|    |_|_____|    |_|_____|    |_______|
//                |            |            |
//               _v_____      _v_____      _v_____
//              |SYM    |    |SYM    |    |SYM    |
//              |"mul"  |    |"a"    |    |"b"    |
//              |_______|    |_______|    |_______|
//
// Programming notes:
//
// 1. Automatic C variables of type "struct atom *" should not be used.
//    Use the global variables p0-p9 instead.
//    Call save() before using p0-p9, then call restore() when finished.
//    The use of p0-p9 is required by the garbage collector.
//
// 2. Do not use NULL for a car or cdr.
//    Use the pointer returned by symbol(NIL) instead.
//    The code does not test for NULL.
</pre>

**Comment by zhouxs1023** [comment]
Can you help me that How to use print_lisp() function?
running in math.exe?

**Comment by georgeweigt** [comment]
print_lisp() is a debugging tool that can be put into the code like a printf.

There is also a lisp function available at runtime (see Help page).

lisp(x)

Evaluates expression x and returns the result as a string in prefix notation. Useful for debugging scripts.

lisp(x^2 + 1)
(+ (^ x 2) 1)

**Comment by zhouxs1023** [comment]
Thank you very much for your help！
To further understand the terminologies used in this project, Can you explain BNF grammar:
