### ISSUE TITLE
arg(-1)=-pi  but Other  math software arg(-1)=pi

### ISSUE THREAD

**Issue by zhouxs1023** [georgeweigt/eigenmath#5]
Other math software arg(-1)=pi,arg(a)=arg(a)
but arg(-1)=-pi, arg(a)=0 in eigenmath

**Comment by georgeweigt** [comment]
Note that exp(i arg(-1)) = -1 and exp(-i arg(-1)) = -1 so both arg(-1) = pi and arg(-1) = -pi are correct. The author chooses arg(-1) = -pi because the sign of the result (i.e., -pi) matches the sign of the argument (i.e., -1). Thx
