### ISSUE TITLE
If the decimal place is too large, the division will be abnormal

### ISSUE THREAD

**Issue by zhouxs1023** [georgeweigt/eigenmath#7]
if we changed  decimal display parameters from sprintf(tbuf, "%g", p->u.d) to sprintf(tbuf, "%.20lf", p->u.d) in display.c,the division will be abnormal as below:
![16220421114105121](https://user-images.githubusercontent.com/905931/82068503-a6a95500-9704-11ea-8600-754588c562bf.png)

**Comment by georgeweigt** [comment]
Try googling "accuracy of C double." thx
