### ISSUE TITLE
EXE file output turn on garble!

### ISSUE THREAD

**Issue by zhouxs1023** [georgeweigt/eigenmath#9]
OS: windows7 x64
Compiling environment：msys2 x64 /msys2 x32

I compiled master code successfully,but When I run eigenmath to calculate 1 / 3, the output will be garbled（as below picture）, and The previous code can correctly output 1 / 3
![screenshot](https://user-images.githubusercontent.com/905931/134528427-1ebf2c84-5ff7-43e2-9ca7-0ef66a3dd679.PNG)

**Comment by georgeweigt** [comment]
Eigenmath uses UTF-8 encoding. The terminal window should have UTF-8 enabled.

**Comment by zhouxs1023** [comment]
I had test latest source code,But it still doesn't display correctly！as below:
![123](https://user-images.githubusercontent.com/905931/137584603-f0e79943-a58f-45f1-aa72-4fb2ef0602ea.PNG)

**Comment by georgeweigt** [comment]
The problem is Terminal is not rendering the following UTF-8 glyphs...
#define BDLL 0xe295b4 // BOX DRAW LIGHT LEFT
#define BDLR 0xe295b6 // BOX DRAW LIGHT RIGHT
BDLL and BDLR can be set to zero to draw spaces instead (see fmt.c)
